build: Обновил зависимости, *Во время разворачивание у себя приложения
Так как являюсь новым контрибьютором репозитория мне необходимо было установить все зависимости, что я сделал следующим образом:
```shell
sudo npm install -g ember@3.1.4

rm -rf node_modules
rm package-lock.json

sudo npm install -g bower
bower install
```

После проделанных выше действий я смог запускать дев-сервер `ember serve`. При этом, несмотря на то, что при запуске тестов лично на моей установке выпадали ошибки:
```shell
not ok 4 Chrome 141.0 - [1 ms] - ESLint | app: controllers/application.js
    ---
        actual: >
            false
        expected: >
            true
        stack: >
                at Object.<anonymous> (http://localhost:7357/assets/tests.js:25:12)
                at runTest (http://localhost:7357/assets/test-support.js:4520:30)
                at Test.run (http://localhost:7357/assets/test-support.js:4506:6)
                at http://localhost:7357/assets/test-support.js:4727:12
                at advanceTaskQueue (http://localhost:7357/assets/test-support.js:4119:6)
                at advance (http://localhost:7357/assets/test-support.js:4100:4)
        message: >
            controllers/application.js should pass ESLint

            12:9 - 'i18n' is assigned a value but never used. (no-unused-vars)
        negative: >
            false
        browser log: |
    ...

not ok 39 Chrome 141.0 - [23 ms] - Unit | Controller | timepath-test-task-response-l: it exists
    ---
        actual: >
            null
        stack: >
            Error: Assertion Failed: Attempting to register an unknown factory: 'controller:timepath-test-task-response-l'
                at new EmberError (http://localhost:7357/assets/vendor.js:30621:25)
                at assert (http://localhost:7357/assets/vendor.js:30871:15)
                at Registry.register (http://localhost:7357/assets/vendor.js:27713:67)
                at exports.default._setupIsolatedContainer (http://localhost:7357/assets/test-support.js:12629:29)
                at exports.default.setupContainer (http://localhost:7357/assets/test-support.js:12461:14)
                at http://localhost:7357/assets/test-support.js:11649:26
                at initializePromise (http://localhost:7357/assets/vendor.js:68301:7)
                at new Promise (http://localhost:7357/assets/vendor.js:68781:35)
                at nextStep (http://localhost:7357/assets/test-support.js:11648:18)
                at exports.default.invokeSteps (http://localhost:7357/assets/test-support.js:11655:14)
        message: >
            Promise rejected before "it exists": Assertion Failed: Attempting to register an unknown factory: 'controller:timepath-test-task-response-l'
        negative: >
            false
        browser log: |
    ...

not ok 42 Chrome 141.0 - [22 ms] - Unit | Route | timepath-test-task-response-l: it exists
    ---
        actual: >
            null
        stack: >
            Error: Assertion Failed: Attempting to register an unknown factory: 'route:timepath-test-task-response-l'
                at new EmberError (http://localhost:7357/assets/vendor.js:30621:25)
                at assert (http://localhost:7357/assets/vendor.js:30871:15)
                at Registry.register (http://localhost:7357/assets/vendor.js:27713:67)
                at exports.default._setupIsolatedContainer (http://localhost:7357/assets/test-support.js:12629:29)
                at exports.default.setupContainer (http://localhost:7357/assets/test-support.js:12461:14)
                at http://localhost:7357/assets/test-support.js:11649:26
                at initializePromise (http://localhost:7357/assets/vendor.js:68301:7)
                at new Promise (http://localhost:7357/assets/vendor.js:68781:35)
                at nextStep (http://localhost:7357/assets/test-support.js:11648:18)
                at exports.default.invokeSteps (http://localhost:7357/assets/test-support.js:11655:14)
        message: >
            Promise rejected before "it exists": Assertion Failed: Attempting to register an unknown factory: 'route:timepath-test-task-response-l'
        negative: >
            false
        browser log: |
    ...
```

В целом работоспособность проекта не нарушена, так как данные ошибки особенность OS на которой я работаю, а также остальные 41 тест были пройдены успешно:
```shell
# tests 44
# pass  41
# skip  0
# fail  3
Testem finished with non-zero exit code. Tests failed.
```