[feat](bookslist-test-task-response): Создал страницу по ТЗ полученном в телеграме
commit e6b473dc92651a86189fa00ebe22902af6992ce1
Author: timofeev.ad <your-email@example.com>
Date:   Wed Oct 22 21:32:47 2025 +0500

    [feat, fix](bookslist-test-task-response): Привел страницу к виду необходимому по ТЗ

    TODO: Поправить тесты

    - Удалил компонент "book-row" и всё с ним связанное
    - Добавил на страницу таблицу
    - Добавил кнопку меняющую цвет страницы
    - Удалил, как я пологаю, неиспользуемые тесты

commit 4c2a1559badcd1867fcc800d9d976dffa26dd4d3
Author: timofeev.ad <your-email@example.com>
Date:   Wed Oct 22 20:09:40 2025 +0500

    refactor: Отрефакторил код, переименновав сущности

commit 7174e7691016ad98ea133464532bf0749ad7424c
Author: timofeev.ad <your-email@example.com>
Date:   Wed Oct 22 18:53:16 2025 +0500

    feat: Изменил страницу-копию до минимально-жизнеспособного виде

commit 2d7c689e7ce0db318345390dd6ea50f09abd5fd1
Author: timofeev.ad <your-email@example.com>
Date:   Wed Oct 22 15:59:13 2025 +0500

    [fix, chore]: Поправил имя файла

commit f15e2618f772dd2966723015bcb21b528bef1ec2
Author: timofeev.ad <your-email@example.com>
Date:   Wed Oct 22 15:47:07 2025 +0500

    chore: Сделал полную копию страницы timepath-test-task-*

commit 7d070c1165a56a18a013489a1d8e4ea6b87ed0df
Author: timofeev.ad <your-email@example.com>
Date:   Wed Oct 22 13:35:01 2025 +0500

    build: Обновил зависимости, *Во время разворачивание у себя приложения

    Так как являюсь новым контрибьютором репозитория мне необходимо было установить все зависимости, что я сделал следующим образом:
    ```shell
    sudo npm install -g ember@3.1.4

    rm -rf node_modules
    rm package-lock.json

    sudo npm install -g bower
    bower install
    ```

    После проделанных выше действий я смог запускать дев-сервер `ember serve`. При этом, несмотря на то, что при запуске тестов лично на моей установке выпадали ошибки:
    ```shell
    not ok 4 Chrome 141.0 - [1 ms] - ESLint | app: controllers/application.js
        ---
            actual: >
                false
            expected: >
                true
            stack: >
                    at Object.<anonymous> (http://localhost:7357/assets/tests.js:25:12)
                    at runTest (http://localhost:7357/assets/test-support.js:4520:30)
                    at Test.run (http://localhost:7357/assets/test-support.js:4506:6)
                    at http://localhost:7357/assets/test-support.js:4727:12
                    at advanceTaskQueue (http://localhost:7357/assets/test-support.js:4119:6)
                    at advance (http://localhost:7357/assets/test-support.js:4100:4)
            message: >
                controllers/application.js should pass ESLint

                12:9 - 'i18n' is assigned a value but never used. (no-unused-vars)
            negative: >
                false
            browser log: |
        ...

    not ok 39 Chrome 141.0 - [23 ms] - Unit | Controller | timepath-test-task-response-l: it exists
        ---
            actual: >
                null
            stack: >
                Error: Assertion Failed: Attempting to register an unknown factory: 'controller:timepath-test-task-response-l'
                    at new EmberError (http://localhost:7357/assets/vendor.js:30621:25)
                    at assert (http://localhost:7357/assets/vendor.js:30871:15)
                    at Registry.register (http://localhost:7357/assets/vendor.js:27713:67)
                    at exports.default._setupIsolatedContainer (http://localhost:7357/assets/test-support.js:12629:29)
                    at exports.default.setupContainer (http://localhost:7357/assets/test-support.js:12461:14)
                    at http://localhost:7357/assets/test-support.js:11649:26
                    at initializePromise (http://localhost:7357/assets/vendor.js:68301:7)
                    at new Promise (http://localhost:7357/assets/vendor.js:68781:35)
                    at nextStep (http://localhost:7357/assets/test-support.js:11648:18)
                    at exports.default.invokeSteps (http://localhost:7357/assets/test-support.js:11655:14)
            message: >
                Promise rejected before "it exists": Assertion Failed: Attempting to register an unknown factory: 'controller:timepath-test-task-response-l'
            negative: >
                false
            browser log: |
        ...

    not ok 42 Chrome 141.0 - [22 ms] - Unit | Route | timepath-test-task-response-l: it exists
        ---
            actual: >
                null
            stack: >
                Error: Assertion Failed: Attempting to register an unknown factory: 'route:timepath-test-task-response-l'
                    at new EmberError (http://localhost:7357/assets/vendor.js:30621:25)
                    at assert (http://localhost:7357/assets/vendor.js:30871:15)
                    at Registry.register (http://localhost:7357/assets/vendor.js:27713:67)
                    at exports.default._setupIsolatedContainer (http://localhost:7357/assets/test-support.js:12629:29)
                    at exports.default.setupContainer (http://localhost:7357/assets/test-support.js:12461:14)
                    at http://localhost:7357/assets/test-support.js:11649:26
                    at initializePromise (http://localhost:7357/assets/vendor.js:68301:7)
                    at new Promise (http://localhost:7357/assets/vendor.js:68781:35)
                    at nextStep (http://localhost:7357/assets/test-support.js:11648:18)
                    at exports.default.invokeSteps (http://localhost:7357/assets/test-support.js:11655:14)
            message: >
                Promise rejected before "it exists": Assertion Failed: Attempting to register an unknown factory: 'route:timepath-test-task-response-l'
            negative: >
                false
            browser log: |
        ...
    ```

    В целом работоспособность проекта не нарушена, так как данные ошибки особенность OS на которой я работаю, а также остальные 41 тест были пройдены успешно:
    ```shell
    # tests 44
    # pass  41
    # skip  0
    # fail  3
    Testem finished with non-zero exit code. Tests failed.
    ```